### ISSUE TITLE
Login button returns a 404 error

### ISSUE THREAD

**Issue by mgutman88** [okta/samples-php#11]
Similar to [this issue posted for Golang](https://github.com/okta/samples-golang/issues/16) and the [issue reported on the Okta forums](https://devforum.okta.com/t/okta-php-samples-not-working/3672/3), I'm experiencing a 404 error when clicking the Login button. mod_rewrite is enabled. Running locally: Apache/2.4.39 (Win32) PHP/7.2.22. Error as follows:

URL (after clicking Login): http://localhost:8080/login
Not Found
The requested URL /login was not found on this server.

**Comment by bretterer** [comment]
We have made some updates to the samples which should resolve this. 

Please let us know if there are still any issues.
