### ISSUE TITLE
/vendor/autoload.php

### ISSUE THREAD

**Issue by arvindvohra** [okta/samples-php#19]
when i am start to using your recommended simple php file then i have found error failed to open stream: No such file or directory "/vendor/autoload.php"

**Comment by bretterer** [comment]
Can you please link to where you are referencing this issue so we can update the documentation please

**Comment by arvindvohra** [comment]
Hi Brain,

I am facing this issue on my localhost server. can you please provide me "check user authentication" code in core php. So, I can test.

Regards,
Arvind vohra
________________________________

**Comment by bretterer** [comment]
I'm sorry, but I still dont understand what the issue is you are having.  This sounds like a php setup issue not being able to find your autoload.php file, not a library/samples issue.
