### ISSUE TITLE
Filesystem loader isn't found.

### ISSUE THREAD

**Issue by CStafford-14** [okta/samples-php#26]
So far, I've been able to do everything up through accessing the login page...
Now, I'm getting issues when starting the okta hosted and custom login.
```Bash
$ composer server:start
> php -S 127.0.0.1:8080 -t ./ ./index.php
[Mon Dec  7 09:59:01 2020] PHP 7.4.3 Development Server (http://127.0.0.1:8080) started
```
Good, right? Now I go to ```localhost:8080``` only to find that the page has no content, just some HTML and Body tags. I also get some of this in the terminal:
```bash
[Mon Dec  7 10:03:12 2020] 127.0.0.1:39470 Accepted
[Mon Dec  7 10:03:12 2020] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /path/to/samples-php-develop/okta-hosted-login/index.php:20
Stack trace:
#0 {main}
  thrown in /path/to/samples-php-develop/okta-hosted-login/index.php on line 20
[Mon Dec  7 10:03:12 2020] 127.0.0.1:39470 Closing
```
Running on Ubuntu 20.04

**Comment by bretterer** [comment]
Hi @CStafford-14 .  There are a few things to check here.  First, did you run `composer install` and make sure all dev dependencies are there as well?  I have seen this issue as well by using `localhost` instead of `127.0.0.1`.  Some systems will not handle IPV4 mapping to localhost -> 127.0.0.1 correctly if IPV6 is available.

**Comment by CStafford-14** [comment]
Yes, I ran ```composer install``` first thing in both folders.
Connecting to 127.0.0.1 gives me the same result.

**Comment by bretterer** [comment]
Are you using composer 1 or composer 2?  I just ran a clean install of the samples with php 7.4.11 without any issues.

Also, make sure that you have your configuration set up correctly. You will need 
```env
CLIENT_ID={yourClientId}
CLIENT_SECRET={yourClientSecret}
ISSUER=https://{yourOktaDomain}.com/oauth2/default
```
in either your systems environment variables, OR in the projects `.env` file. You can also try starting the servers from the root of the repo using `composer sample:custom-login`

From the original error you posted, it seems likely that something failed with the composer install or update. I would want to see the logs of your install there if possible.

**Comment by CStafford-14** [comment]
Ah, I think I'm using version 1. I installed it right before grabbing the repo from my package manager. I guess Composer isn't up-to-date on Ubuntu's end.

EDIT: Using 2.0.8 now, still getting the issue.

**Comment by CStafford-14** [comment]
Composer log:
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - fgrosse/phpasn1 is locked to version 2.0.1 and an update of this package was not requested.
    - fgrosse/phpasn1 2.0.1 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
  Problem 2
    - mdanter/ecc is locked to version v0.5.0 and an update of this package was not requested.
    - mdanter/ecc v0.5.0 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
  Problem 3
    - php-http/curl-client is locked to version v1.7.0 and an update of this package was not requested.
    - php-http/curl-client v1.7.0 requires ext-curl * -> it is missing from your system. Install or enable PHP's curl extension.
  Problem 4
    - fgrosse/phpasn1 2.0.1 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
    - spomky-labs/jose v7.0.1 requires fgrosse/phpasn1 ^2.0 -> satisfiable by fgrosse/phpasn1[2.0.1].
    - spomky-labs/jose is locked to version v7.0.1 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

Generally, there's something near the bottom telling you if there were issues or not... I didn't scroll up until now.

**Comment by bretterer** [comment]
Thanks for the log. It sounds like you are missing some requirements on your system, which is typical for Ubuntu systems.  Install `ext-gmp` and `ext-curl` for your version of PHP. Once you do that, remove your `vendor` folder and composer.lock, and try the composer install again.

Let us know if that helps

**Comment by CStafford-14** [comment]
Yep, that's what I needed. Thanks!

**Comment by bretterer** [comment]
Glad we could help!  We will look at updating our readme to make sure we include the need for those two extensions. Please let us know if there is anything else we can do for you.
