### ISSUE TITLE
simple issue when run on localhost.

### ISSUE THREAD

**Issue by sea-sol** [okta/samples-php#33]
when I click login button.
it shows this error
`HP Fatal error:  Uncaught Error: Call to undefined function Jose\KeyConverter\gmp_strval()`
and if I refresh, 
it shows this message
`Could not exchange code for an access token`

**Comment by laura-rodriguez** [comment]
Hi @Rolland-K ,

Thanks for submitting this issue. 

I've created an internal issue to be reviewed and prioritized by the team.

Internal Ref: OKTA-415483

**Comment by bretterer** [comment]
Hi @Rolland-K 

This issue typically means that you don't have gmp installed in your PHP installation.

Please take a look at the gmp install guide at https://www.php.net/manual/en/gmp.installation.php and see if that resolves your issue.
