### ISSUE TITLE
application hung after this line php -S 127.0.0.1:8080 -t . index.php

### ISSUE THREAD

**Issue by lnguyen12** [okta/samples-php#4]
Hi Brian,

I'm trying to install this but when I ran command "> composer server:start", it just returns this line "> php -S 127.0.0.1:8080 -t . index.php" and then froze. Nothing happens. Did I miss anything?

Centos 7
Apache 2.4.10
PHP 7.1.16

Thanks,

**Comment by bretterer** [comment]
Hi @lnguyen12 

When you started the server with `composer server:start` from within one of the samples in the repo, did you try to go to `127.0.0.1:8080` in your web browser?  If you did, what shows there?

-Brian

**Comment by lnguyen12** [comment]
I got this below message

This page isn’t working

*drupal8.sjlibrary.org <http://drupal8.sjlibrary.org>* didn’t send any data.
ERR_EMPTY_RESPONSE

Thanks,

Lyna

**Comment by bretterer** [comment]
It appears that there may be something not right with your local configuration.  The samples here would not produce any error messages regarding anything in drupal.  Make sure that you have no other servers running.  You can run the following command to kill anything that is listening on port 8080 and 8000

```
kill $(lsof -t -i:8080; lsof -t -i:8000)
```

Give that a try and get back to me.

**Comment by lnguyen12** [comment]
still the same error.

Thanks,

Lyna

**Comment by bretterer** [comment]
I am still stuck on why it is reporting drupal8  can you send a screenshot of your full web browser when trying to visit the sample.  If you can also include a screen shot of your terminal after issuing the command, that may help out.

**Comment by lnguyen12** [comment]
here it is. I also changed 127.0.0.1 to our hostname in composer.json file,
but it still doesn't work.



Thanks,

Lyna

**Comment by bretterer** [comment]
Lyna,

Could you please send me your apache and php logs from the timeframe that you are experiencing this?

**Comment by lnguyen12** [comment]
Hi Brian,

the apache and php doesn't generate any errors when this is run.

Thanks,

Lyna
