### ISSUE TITLE
Debuging "Error fetching access token"

### ISSUE THREAD

**Issue by calinpavel787** [okta/samples-php#52]
Hello,

I'm not actually a PHP developer, but I'm just trying to help my team. 

After the OKTA login successful, we receive the message from the title of this issue.

```
if(!isset($response->access_token)) {
        die('Error fetching access token');
}
```

If you are in this situation, on what you should look first? Or how you debug this? 

In any case, is it possible that the metadata url of OKTA has been changed recently? 

Regards.

**Comment by laura-rodriguez** [comment]
Hi @calinpavel787 ,

I suggest you inspect all your requests and responses with FIddler for example and make sure your Okta configuration is OK.
You can post a Fiddler log here making sure you're not sharing secrets so we can help you better.

**Comment by calinpavel787** [comment]
Hi @laura-rodriguez,

Thank you very much for the support you gave me so far. 

I was using Fiddler, exactly like you told me, and the only thing that I'm finding weird is, after the successfully login is the "Expires" header value on the URL, where I'm redirected after the login, that says ```Thu, 19 Nov 1981 08:52:00 GMT``` . 

Do you think that's the issue? If so, if I remember correctly (because right now I don't have access to the Okta application settings), we set the refresh token to rotate after every use. I'm going to check once more tomorrow to confirm.

<img width="609" alt="Screen Shot 2022-05-08 at 16 13 14" src="https://user-images.githubusercontent.com/99649063/167297829-3f2e51fb-4d1f-4b6c-82c7-40d6713968d8.png">

**Comment by ghost** [comment]
This is likely the issue here. 

Were you able to resolve your issue here?
