### ISSUE TITLE
Hosted Login README: Missing link to OIDC WEB Setup Instructions

### ISSUE THREAD

**Issue by keithdechant** [okta/samples-php#8]
The README for the "Okta Hosted Login" demo app has a link with no URL that is not rendering correctly in Markdown:

"This is done from the Okta Developer Console and you can find instructions [here][OIDC WEB Setup Instructions]."

See https://github.com/okta/samples-php/blame/develop/okta-hosted-login/README.md#L9

That link would have been very useful to me in my research on how to integrate with Okta.

**Comment by bretterer** [comment]
@keithdechant I will get this updated, but for your reference, it should link to https://developer.okta.com/authentication-guide/implementing-authentication/implicit#1-setting-up-your-application
