### ISSUE TITLE
Redirecting to 404 error on custom login

### ISSUE THREAD

**Issue by genloz** [okta/samples-php#9]
Hi!

Just wondering if you could please point me in the right direction?
I'm consistently being redirected to a 404 error page on my dev-xxxx-admin.oktapreview.com. 
The app loads successfully, I click "login" and am redirected to a login prompt. This correctly stops me if incorrect, but if the credentials are correct I see a 404 error with an attempt at accessing the callback url. 

This 404 url ends with scope=openid email
which is encoded with a %2520 in the space. 
This appears to be breaking the callback page. 

Any advice?

Thanks!

**Comment by bretterer** [comment]
Can you show me what the URL is your are using for your config of the samples?  

IE: what is this in your config file?  
```
 ISSUER=https://{yourOktaDomain}.com/oauth2/default
```

**Comment by genloz** [comment]
In the .env file it's as below:
ISSUER=https://dev-999999-admin.oktapreview.com/oauth2/default
But with my id instead of 999999

**Comment by mraible** [comment]
Try removing the "-admin" part of your URL.

**Comment by bretterer** [comment]
@genloz Ah, I see the problem there.  You are including the `-admin` part in the ISSUER.  If you remove the `-admin` part of the url and only use your `OktaDomain` part of the url, you should be able to log in.

> Issuer - This is the URL of the authorization server that will perform authentication. All Developer Accounts have a "default" authorization server. The issuer is a combination of your Org URL (found in the upper right of the console home page) and /oauth2/default. For example, https://dev-1234.oktapreview.com/oauth2/default.

**Comment by genloz** [comment]
Perfect! That worked thanks very much both @mraible and @bretterer
